[tool.poetry]
name = "curso-django"
version = "0.1.0"
description = "Projeto desenvolvido no Curso Django da Python Pro"
authors = ["Felipe Antonio <felipe.antonio.online@proton.me>"]
license = "AGPL"

[tool.poetry.dependencies]
python = "3.10.5"
Django = "^4.0.6"
gunicorn = "^20.1.0"
python-decouple = "^3.6"
dj-database-url = "^0.5.0"
psycopg2-binary = "^2.9.3"
django-s3-folder-storage = "^0.5"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
flake8 = "^4.0.1"
pytest = "^7.1.2"
coverage = "^6.4.1"
pytest-cov = "^3.0.0"
pytest-django = "^4.5.2"
pytest-mock = "^3.8.2"
Sphinx = "^5.0.2"
ggshield = "^1.12.0"
pre-commit = "^2.19.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.pytest.ini_options]
minversion = "6.0"
DJANGO_SETTINGS_MODULE = "pypro.settings"
addopts = "-ra -q --doctest-modules"
