# Generated by Django 4.1 on 2022-08-30 18:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aperitivos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="creation",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
